openapi: 3.0.0
info:
  title: Service template
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0
paths:
  /health-check:
    get:
      tags:
        - Core
      responses:
        '200':
          description: Health state of the service
          content:
            application/json:
              schema:
                type: object
                properties:
                  state:
                    type: string
                    example: OK
                  uptime:
                    type: string
                    example: 2000s
